# Generated by Django 5.2.1 on 2025-05-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('temporada', models.CharField(max_length=9)),
                ('api_code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('api_code', models.IntegerField(unique=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('placar_mandante', models.IntegerField()),
                ('placar_visitante', models.IntegerField()),
                ('codigo_api', models.IntegerField(unique=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.campeonato')),
                ('time_mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='core.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='core.time')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posição', models.CharField(max_length=50)),
                ('api_code', models.IntegerField(unique=True)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to='core.time')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticasJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posse_bola', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finalizacoes', models.IntegerField(default=0)),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartoes_vermelhos', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='core.jogo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.time')),
            ],
        ),
    ]
