# Generated by Django 5.2.1 on 2025-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_matchevent_teamstatistics_delete_matchstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
