# Generated by Django 5.2.1 on 2025-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='api_code',
        ),
        migrations.RemoveField(
            model_name='time',
            name='campeonato',
        ),
        migrations.AddField(
            model_name='time',
            name='fundacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pais',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
