# Generated by Django 5.2.1 on 2025-06-11 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_appearences_player_assists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='venue',
            new_name='referee',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='round',
            new_name='venue_city',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='core.team'),
        ),
    ]
