# Generated by Django 5.2.1 on 2025-06-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_venue_match_referee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('assist', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('minute', models.IntegerField()),
                ('extra_minute', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_on_goal', models.IntegerField(blank=True, null=True)),
                ('shots_off_goal', models.IntegerField(blank=True, null=True)),
                ('total_shots', models.IntegerField(blank=True, null=True)),
                ('blocked_shots', models.IntegerField(blank=True, null=True)),
                ('shots_inside_box', models.IntegerField(blank=True, null=True)),
                ('shots_outside_box', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('corner_kicks', models.IntegerField(blank=True, null=True)),
                ('offsides', models.IntegerField(blank=True, null=True)),
                ('ball_possession', models.CharField(blank=True, max_length=10, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('passes', models.IntegerField(blank=True, null=True)),
                ('accurate_passes', models.IntegerField(blank=True, null=True)),
                ('pass_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.DeleteModel(
            name='MatchStatistic',
        ),
    ]
