# Generated by Django 5.2.1 on 2025-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_league_last_fetched_at_match_last_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='events_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='events_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
