# Generated by Django 5.2.1 on 2025-11-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match_events_fetched_at_match_stats_fetched_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_penalties',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_penalties',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue_capacity',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='accurate_passes',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='blocked_shots',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='fouls',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='pass_percentage',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='shots_inside_box',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='shots_outside_box',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='yellow_cards',
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
