# Generated by Django 5.2 on 2026-01-08 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_match_away_penalties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=50)),
                ('calculated_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('implied_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_value_bet', models.BooleanField(default=False)),
                ('confidence', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.match')),
                ('bookmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookmaker')),
            ],
            options={
                'ordering': ['-expected_value'],
                'indexes': [models.Index(fields=['is_value_bet', '-expected_value'], name='core_betrec_is_valu_0002d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('draw_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('away_win_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('over_25_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('under_25_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btts_yes_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btts_no_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('odds_api_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookmaker')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='core.match')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'bookmaker'], name='core_matcho_match_i_d6f348_idx')],
                'unique_together': {('match', 'bookmaker')},
            },
        ),
    ]
