# Generated by Django 5.2 on 2026-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookmaker_betrecommendation_matchodds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmaker',
            name='is_brazilian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='last_api_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
