# Generated by Django 5.2 on 2026-02-11 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bookmaker_is_brazilian_matchodds_last_api_fetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_limit', models.IntegerField(default=5)),
                ('probabilities', models.JSONField(default=dict)),
                ('team_rates', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('best_by_market', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.match')),
            ],
            options={
                'indexes': [models.Index(fields=['computed_at'], name='core_matcha_compute_4cf8cc_idx')],
            },
        ),
    ]
